name: Sonar Cloud Code Analysis
on:
 push:
  branches:
   - master
 pull_request:
  branches:
   - master
jobs:
 sonarcloud:
  name: SonarCloudAnalysis
  runs-on: ubuntu-latest
  steps:
   - name: Checkout the code
     uses: actions/checkout@v4
   - name: Set up Python
     uses: actions/setup-python@v5
     with:
      python-version: 3.13.2
   - name: Install Dependecies
     run: |
       python -m pip install --upgrade pip
       pip install -r day1/requirements.txt
       pip install coverage
   #- name: Run tests with coverage
     #run: |
      #coverage run -m unittest discover
      #coverage xml
   - name: Run SonarCloud Scan
     uses: SonarSource/sonarcloud-github-action@v2.1.1
     with:
      projectBaseDir: .
     env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
     
   
