name: Deploy AWS Django


on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy (dev, test, prod)'
        required: true
        default: '.env.dev'
        type: choice
        options:
          - env.dev
          - env.test
          - env.prod

  
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
         token: ${{ secrets.GITHUBTOKEN }}
         ref: main

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SECRET_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -i ec2_key.pem -o StrictHostKeyChecking=no" ./employeeapidocker ${{ secrets.EC2_HOST }}:/home/ubuntu/trainingjun2025

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set environment variable for Docker Compose
        run: | 
          #ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} " 
           echo "DJANGO_ENV=${{ github.event.inputs.env }}" >> $GITHUB_ENV
           echo ${DJANGO_ENV}

      - name: Run Docker Compose
        run: |
          pwd
          ls
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} "
          pwd
          ls
          cd  ./trainingjun2025/employeeapidocker
          #docker network create mtsnetwork
          sudo docker-compose --env-file=env.dev up -d --build"

     
