name: Deploy Django App to EC2

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy (dev, test, prod)'
        required: true
        default: '.env.dev'
        type: choice
        options:
          - .env.dev
          - .env.test
          - .env.prod

  push:
    branches: [ main ]
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.EC2_SECRET_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -i ec2_key.pem -o StrictHostKeyChecking=no" ./employeeapidocker ${{ secrets.EC2_HOST }}:/home/ubuntu/trainingjun2025

      - name: Run Python app on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} "
            cd /home/ubuntu/trainingjun2025/day1 &&
            ${{ secrets.EC2_PYTHON_PATH || 'python3' }} currentdatetime.py
          "
