# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
env:
  FOLDERNAME: 'day1'
  GITFOLDERNAME: ${{vars.FOLDERNAME}}
  GITUSERNAME: ${{vars.USERNAME}}
jobs:
  combined:
    runs-on: ubuntu-latest
    steps:
      - name: Use global environment variable
        run: echo "Folder Name:${FOLDERNAME}"
      - name: Use github environment variable
        run: echo "Folder Name:$GITFOLDERNAME and Username:$USERNAME"
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13.2
      uses: actions/setup-python@v3
      with:
        python-version: "3.13.2"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

        if [ -f ${FOLDERNAME}/requirements.txt ]; then pip install -r ${FOLDERNAME}/requirements.txt; fi

    - name: Run the Python Code
      run: |
        python ${FOLDERNAME}/currentdateime.py
