name: Send data Work Flow
permissions:
 contents: write
on: 
 workflow_dispatch:

jobs:
  call-reusable:
   uses: ./.github/workflows/reusablewf.yml
   with: 
     cardno: 427843858490
     cardtype: visa
     
