name: Invoke Send Data Work Flow
permissions:
 contents: write
on: 
 workflow_dispatch:
   inputs:
    cardno: 
      description: 'Enter Credit Card No'
      required: true
      default: '123456789012345'
    cardtype:
      description: 'Choose Card Type'
      required: true
      type: choice
      options:
       - master
       - visa
       - amex
      default: master 
jobs:
  call-reusable:
   uses: ./.github/workflows/reusablewf.yml
   name: wf2job
   with: 
     cardno: "${{ github.event.inputs.cardno }}" 
     cardtype: "${{ github.event.inputs.cardtype }}" 
    
  print-result:
   runs-on: ubuntu-latest
   needs: call-reusable
   steps:
     - name: Print return message
       run: ${{ needs.call-reusable.outputs.message }}

    
     
